version: '3.3'
services:
  db:
    image: mysql:5.6.34
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    volumes:
      - ./db:/var/lib/mysql
  web:
    build: .
    command:  bash -c "rm -f tmp/pids/server.pid && ./init.sh"
    volumes:
      - .:/myapp
    ports:
     - "3000:3000"
    depends_on:
      - db


